[project]
name = "ssh-telegram-manager"
version = "1.0.0"
description = "Python app to launch sshd server from Telegram"
requires-python = ">=3.10,<4.0"
authors = [{name = "turulomio", email = "turulomio@yahoo.es"}]
license = "GPL-3.0-only"
readme = "README.md"
dependencies = [ # This is for PEP 621 core dependencies
    "python-telegram-bot>=22.7",
]

[project.urls]
homepage = "https://github.com/turulomio/ssh_telegram_manager/"
repository = "https://github.com/turulomio/ssh_telegram_manager/"
changelog = "https://github.com/turulomio/ssh_telegram_manager#changelog"

[project.scripts]
ssh_telegram_manager='ssh_telegram_manager.core:main'

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.3"
poethepoet = ">=0.46.0"
coverage = ">=7.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
release = { script = "ssh_telegram_manager.poethepoet:release" }
translate = { script = "ssh_telegram_manager.poethepoet:translate" }
pytest = { script = "ssh_telegram_manager.poethepoet:pytest" }
coverage = { script = "ssh_telegram_manager.poethepoet:coverage" }
